package dk.jnie.dragunzip.view;

public enum ComponentID {
	TXTF_FOLDER, B_START, B_STOP, MENU_CONFIG_EDIT, MENU_CONFIG_EXIT, MENU_HELP_ABOUT,MENU_CONFIG_START, MENU_CONFIG_STOP, CHK_CLEAR_FOLDER, MENU_VIEW_UK, MENU_VIEW_DK, TXTF_TIMER;
}
